
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: momentum_investments
      show-sql: true
    defer-datasource-initialization: true
  sql:
    init:
      schema-locations: classpath:database/database-creation.sql
      mode: always

h2-server:
  port: 11111

file-manager:
  aws:
    upload-bucket: raw-csv-form
    output-bucket: pfd-form
    region: us-west-1
    endpoint: http://localhost:4566
  atmoz-sftp:
    username: foo
    password: pass
    host: localhost
    port: 2222
