
spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:momentum_investments
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        default_schema: momentum_investments
      database-platform: org.hibernate.dialect.H2Dialect
      show-sql: true
    defer-datasource-initialization: true
  sql:
    init:
      schema-locations: classpath:database/database-creation.sql
      mode: always

h2-server:
  port: 11111

file-manager:
  aws:
    upload-bucket: raw-csv-form
    output-bucket: pfd-form
    region: us-west-1
    endpoint: http://localhost:4566

